name: arm
channels:
  - conda-forge
dependencies:
  - act-atmos
  - affine
  - aiobotocore
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aioitertools
  - aioredis
  - aiosignal
  - aiosqlite
  - altair
  - anyio
  - appdirs
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - arm_pyart
  - asttokens
  - async-retriever
  - async-timeout
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - bleach
  - blosc
  - bokeh
  - boost-cpp
  - botocore
  - branca
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - cartopy
  - cattrs
  - cchardet
  - certifi
  - cffi
  - cfitsio
  - cftime
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - colorama
  - colorcet
  - contextily
  - contourpy
  - cryptography
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - debugpy
  - decorator
  - defusedxml
  - distributed
  - eccodes
  - entrypoints
  - esmf
  - exceptiongroup
  - executing
  - expat
  - fftw
  - fiona
  - flit-core
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - freexl
  - fribidi
  - frozenlist
  - fsspec
  - gdal
  - geographiclib
  - geopandas
  - geopandas-base
  - geopy
  - geos
  - geotiff
  - gettext
  - giflib
  - glib
  - glib-tools
  - graphite2
  - gsl
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf4
  - hdf5
  - heapdict
  - holoviews
  - hvplot
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - ipykernel
  - ipympl
  - ipython
  - ipython_genutils
  - ipywidgets
  - itsdangerous
  - jasper
  - jedi
  - jinja2
  - jmespath
  - joblib
  - jpeg
  - jplephem
  - json-c
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab_pygments
  - jupyterlab_widgets
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libaec
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libclang13
  - libcurl
  - libcxx
  - libdap4
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgdal
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libkml
  - liblapack
  - libllvm15
  - libnetcdf
  - libnghttp2
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - librttopo
  - libsodium
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libtiff
  - libvorbis
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - libzip
  - libzlib
  - llvm-openmp
  - locket
  - loguru
  - lxml
  - lz4
  - lz4-c
  - magics
  - magics-python
  - mapclassify
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mercantile
  - metpy
  - mistune
  - msgpack-python
  - multidict
  - munch
  - munkres
  - mysql-common
  - mysql-libs
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - nco
  - nctoolkit
  - ncurses
  - nest-asyncio
  - netcdf-fortran
  - netcdf4
  - networkx
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numpy
  - openjpeg
  - openssl
  - ossuuid
  - owslib
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - panel
  - pango
  - param
  - parso
  - partd
  - patsy
  - pcre
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pint
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - ply
  - pooch
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - py3dep
  - pycares
  - pycparser
  - pyct
  - pyct-core
  - pygeoogc
  - pygeos
  - pygeoutils
  - pygments
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyqt5-sip
  - pyrsistent
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-forge
  - python_abi
  - pytz
  - pyviz_comms
  - pyyaml
  - pyzmq
  - qt-main
  - qtconsole
  - qtconsole-base
  - qtpy
  - rasterio
  - readline
  - requests
  - requests-cache
  - rioxarray
  - rtree
  - s3fs
  - scikit-learn
  - scikit-posthocs
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - setuptools-scm
  - setuptools_scm
  - sgp4
  - shapely
  - simplejson
  - sip
  - six
  - skyfield
  - snappy
  - sniffio
  - snuggs
  - sortedcontainers
  - soupsieve
  - sqlite
  - stack_data
  - statsmodels
  - tblib
  - tempest-remap
  - terminado
  - threadpoolctl
  - tiledb
  - tinycss2
  - tk
  - toml
  - tomli
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzcode
  - tzdata
  - udunits2
  - ujson
  - unicodedata2
  - url-normalize
  - urllib3
  - vega
  - versioneer
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - wrapt
  - xarray
  - xerces-c
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - xz
  - yaml
  - yarl
  - zeromq
  - zict
  - zipp
  - zlib
  - zstd
  - pip:
    - cdo
