name: arm
channels:
  - conda-forge
dependencies:
  - act-atmos=1.2.0
  - affine=2.3.1
  - aiobotocore=2.4.0
  - aiodns=3.0.0
  - aiohttp=3.8.3
  - aiohttp-client-cache=0.7.3
  - aioitertools=0.11.0
  - aioredis=2.0.1
  - aiosignal=1.3.1
  - aiosqlite=0.17.0
  - altair=4.2.0
  - anyio=3.6.2
  - appdirs=1.4.4
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arm_pyart=1.14.0
  - asttokens=2.1.0
  - async-retriever=0.3.6
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - blosc=1.21.1
  - bokeh=2.4.3
  - boost-cpp=1.78.0
  - botocore=1.27.59
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - cartopy=0.21.0
  - cattrs=22.2.0
  - cchardet=2.1.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - cftime=1.6.2
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.0
  - colorama=0.4.6
  - colorcet=3.0.1
  - contextily=1.2.0
  - contourpy=1.0.6
  - cryptography=38.0.4
  - curl=7.86.0
  - cycler=0.11.0
  - cython=0.29.32
  - cytoolz=0.12.0
  - dask=2022.10.2
  - dask-core=2022.10.2
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2022.10.2
  - eccodes=2.27.1
  - entrypoints=0.4
  - esmf=8.4.0
  - exceptiongroup=1.0.2
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - fiona=1.8.22
  - flit-core=3.8.0
  - folium=0.13.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - freexl=1.0.6
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - gdal=3.5.3
  - geographiclib=1.52
  - geopandas=0.12.1
  - geopandas-base=0.12.1
  - geopy=2.3.0
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - graphite2=1.3.13
  - gsl=2.7
  - gst-plugins-base=1.21.2
  - gstreamer=1.21.2
  - harfbuzz=5.3.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - heapdict=1.0.1
  - holoviews=1.15.2
  - hvplot=0.8.2
  - icu=70.1
  - idna=3.4
  - importlib-metadata=5.0.0
  - importlib_resources=5.10.0
  - ipykernel=6.17.1
  - ipympl=0.9.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - itsdangerous=2.1.2
  - jasper=2.0.33
  - jedi=0.18.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - jpeg=9e
  - jplephem=2.18
  - json-c=0.16
  - jsonschema=4.17.0
  - jupyter=1.0.0
  - jupyter_client=7.3.4
  - jupyter_console=6.4.4
  - jupyter_core=5.0.0
  - jupyter_server=1.23.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.3
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.14
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.6
  - libclang13=15.0.6
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.5.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm15=15.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=15.0.4
  - locket=1.0.0
  - loguru=0.6.0
  - lxml=4.9.1
  - lz4=4.0.2
  - lz4-c=1.9.3
  - magics=4.12.1
  - magics-python=1.5.6
  - mapclassify=2.4.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mercantile=1.2.1
  - metpy=1.3.1
  - mistune=2.0.4
  - msgpack-python=1.0.4
  - multidict=6.0.2
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclassic=0.4.8
  - nbclient=0.7.0
  - nbconvert=7.2.5
  - nbconvert-core=7.2.5
  - nbconvert-pandoc=7.2.5
  - nbformat=5.7.0
  - nco=5.1.3
  - nctoolkit=0.2.2
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - netcdf-fortran=4.6.0
  - netcdf4=1.6.1
  - networkx=2.8.8
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.78
  - numpy=1.23.4
  - openjpeg=2.5.0
  - openssl=3.0.7
  - ossuuid=1.6.2
  - owslib=0.27.2
  - packaging=21.3
  - pandas=1.5.1
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - panel=0.14.1
  - pango=1.50.12
  - param=1.12.2
  - parso=0.8.3
  - partd=1.3.0
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pint=0.20.1
  - pip=22.3.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.6.0
  - poppler=22.11.0
  - poppler-data=0.4.11
  - postgresql=15.1
  - proj=9.1.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.32
  - prompt_toolkit=3.0.32
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py3dep=0.13.7
  - pycares=4.0.0
  - pycparser=2.21
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pygeoogc=0.13.7
  - pygeos=0.13
  - pygeoutils=0.13.9
  - pygments=2.13.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyproj=3.4.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.2
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-forge=18.6.0
  - python_abi=3.10
  - pytz=2022.6
  - pyviz_comms=2.2.1
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - qtconsole=5.4.0
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - rasterio=1.3.3
  - readline=8.1.2
  - requests=2.28.1
  - requests-cache=0.9.6
  - rioxarray=0.13.1
  - rtree=1.0.1
  - s3fs=2022.11.0
  - scikit-learn=1.1.3
  - scikit-posthocs=0.7.0
  - scipy=1.9.3
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - send2trash=1.8.0
  - setuptools=65.5.1
  - setuptools-scm=7.0.5
  - setuptools_scm=7.0.5
  - sgp4=2.21
  - shapely=1.8.5
  - simplejson=3.18.0
  - sip=6.7.4
  - six=1.16.0
  - skyfield=1.45
  - snappy=1.1.9
  - sniffio=1.3.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.6.1
  - statsmodels=0.13.5
  - tblib=1.7.0
  - tempest-remap=2.1.6
  - terminado=0.17.0
  - threadpoolctl=3.1.0
  - tiledb=2.11.3
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.1
  - tqdm=4.64.1
  - traitlets=5.5.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzcode=2022f
  - tzdata=2022f
  - udunits2=2.2.28
  - ujson=5.5.0
  - unicodedata2=15.0.0
  - url-normalize=1.4.3
  - urllib3=1.26.11
  - vega=3.6.0
  - versioneer=0.28
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.3
  - wrapt=1.14.1
  - xarray=2022.11.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - cdo=
